# Generated by Django 4.2.5 on 2023-10-01 19:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_servicerequst"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ServiceRequst",
            new_name="ServiceRequest",
        ),
    ]
