# Generated by Django 4.2.5 on 2023-10-01 20:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_rename_servicerequst_servicerequest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicerequest",
            name="service",
        ),
    ]
